# Generated by Django 4.2.5 on 2023-10-01 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_product_current_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=datetime.datetime(2023, 10, 1, 7, 6, 28, 375024, tzinfo=datetime.timezone.utc), verbose_name='Default description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffrequest',
            name='name',
            field=models.CharField(default='2023-10-01 12:00:00', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.product')),
            ],
        ),
    ]
